name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            # Checkout repository folder
            cd ~/${{ github.event.repository.name }}

            # Pull any changes from upstream repository
            git pull

            # Build and deploy images
            docker-compose build
            docker-compose up --no-deps -d